service: serverless-example-v1

plugins:
  - serverless-google-cloudfunctions
  - serverless-plugin-typescript

provider:
  name: google
  region: asia-south1
  project: helpful-helper-364816
  runtime: nodejs16

functions:
  hello:
    handler: hello
    events:
      - http: path
