pipeline {
  agent any
  environment {
    CLOUDSDK_CORE_PROJECT='flawless-helper-376817'
    CLIENT_EMAIL_ID='1048415450475-compute@developer.gserviceaccount.com'
    GCLOUD_CREDS=credentials('gcloud-creds')
    GOOGLE_APPLICATION_CREDENTIALS=credentials('gcloud-creds')
  }
  stages {
    stage('version-testing') {
      steps {
        sh '''
          gcloud version
          gcloud auth activate-service-account --key-file="$GCLOUD_CREDS"
          gcloud compute zones list
          whoami
        '''
      }
    }
    stage('input/deployment') {    
      input {
        message "Do you want to approve the deployment?"
        ok "Submit"
      }
      steps {
        sh '''
          node --version
          serverless --version
          serverless --help
          sudo npm install --save serverless-google-cloudfunctions
          serverless deploy
        '''
      }
    }
  }
}
