pipeline {
  agent any
  environment {
    CLOUDSDK_CORE_PROJECT='helpful-helper-364816'
    CLIENT_EMAIL_ID='jenkins@helpful-helper-364816.iam.gserviceaccount.com'
    GCLOUD_CREDS=credentials('gcloud-creds')
    GOOGLE_APPLICATION_CREDENTIALS=credentials('gcloud-creds')
  }
  stages {
    stage('version-testing') {
      steps {
        sh '''
          gcloud version
          gcloud auth activate-service-account --key-file="$GCLOUD_CREDS"
          gcloud compute zones list
          whoami
          gcloud auth list
        '''
      }
    }
    stage('input') {
      input {
        message "What is your first name?"
        ok "Submit"
        parameters {
          string(defaultValue: 'Dave', name: 'FIRST_NAME', trim: true) 
        }
      }
      steps {
        echo "Good Morning, $FIRST_NAME"
        sh '''
          hostname
          cat /etc/redhat-release
        '''
      }
    }
    stage('version check') {
      steps {
        sh '''
          node --version
          serverless --version
          serverless --help
          sudo npm install --save serverless-google-cloudfunctions
          serverless deploy
        '''
      }
    }
  }
  post {
    always {
      sh 'gcloud auth revoke $CLIENT_EMAIL_ID'
    }
  }
}
